Inline `filter-iterator` and `reverse-arguments`
ericcornelissen/bash-parser pull request #7
Opened 2024-06-04 22:36 UTC by sockmaster27

`filter-iterator` does not contain a license field in its `package.json`, which is a problem for automated license compatibility checkers. The PR with the fix has been open for over a year with no response: https://github.com/jb55/filter-iterator/pull/1

2024-06-07 11:13 UTC, ericcornelissen requested changes
Thanks for the contribution, I think it makes sense to do this.

Could you just change it so that it's included in the [`vendored`](https://github.com/ericcornelissen/bash-parser/tree/8b429baaf5c8a989f257762d39a83a8c8a3c8ae8/src/vendored) directory similar to other vendored dependencies and include a comment in the end along the lines of previously vendored dependencies? Thanks!

2024-06-07 13:59 UTC, ericcornelissen approved these changes

2024-06-07 14:02 UTC, merged

2024-06-07 14:06 UTC, ericcornelissen commented
Thank you for the contribution! I'll look into publishing this over the weekend (as it's a manual process and I'm not at my PC). Feel free to ping me here sometime next week if I didn't publish anything yet :slightly_smiling_face:

2024-06-08 10:52 UTC, ericcornelissen commented
This is now released with [v0.5.3](https://www.npmjs.com/package/@ericcornelissen/bash-parser/v/0.5.3)

2024-06-08 12:28 UTC, sockmaster27 commented
Still not v1.0.0? 😅

2024-06-08 12:31 UTC, ericcornelissen commented
Any reason it should be v1.0.0? I'm inclined to keep the major (and ideally minor) version identical to the [original project](https://github.com/vorpaljs/bash-parser).

2024-06-08 12:39 UTC, sockmaster27 commented
That is completely reasonable. I just find it a bit funny-looking that a package with seemingly no significant changes in the last 7 years is not considered 'stable'.